export type ReportEndpoint =
  | "/subjects/download/excel"
  | "/station_names/download/excel"
  | "/work_types/download/excel"
  | "/work_type_codes/download/excel"
  | "/orgs/download/excel"
  | "/trains/download/excel"
  | "/detector_types/download/excel"
  | "/detectors/download/excel"
  | "/documents/download/excel"
  | "/stations/download/excel"
  | "/maintenance_teams/download/excel";

export interface ReportConfig {
  label: string;
  fields: string[];
  fieldsRu: Record<string, string>;
}

export const REPORT_SETTINGS: Record<ReportEndpoint, ReportConfig> = {
  "/station_names/download/excel": {
    label: "Наименование станций",
    fields: ["globalSearch", "title", "comment", "includeDeleted"],
    fieldsRu: {
      globalSearch: "Глобальный поиск",
      title: "Наименование станции",
      comment: "Комментарий",
      includeDeleted: "Включать удаленные",
    },
  },
  "/orgs/download/excel": {
    label: "Подразделения и организации",
    fields: [
      "globalSearch",
      "title",
      "comment",
      "shortTitle",
      "responsible",
      "jobTitle",
      "includeDeleted",
    ],
    fieldsRu: {
      globalSearch: "Глобальный поиск",
      title: "Полное наименование",
      comment: "Комментарий",
      shortTitle: "Сокращенное наименование",
      responsible: "Ответственный",
      jobTitle: "Должность",
      includeDeleted: "Включать удаленные",
    },
  },
  "/maintenance_teams/download/excel": {
    label: "Обслуживающие бригады",
    fields: ["globalSearch", "orgId", "title", "comment", "includeDeleted"],
    fieldsRu: {
      globalSearch: "Глобальный поиск",
      orgId: "Обслуживаемая организация",
      title: "Название бригады",
      comment: "Комментарий",
      includeDeleted: "Включать удаленное",
    },
  },
  "/detector_types/download/excel": {
    label: "Типы датчиков",
    fields: ["globalSearch", "title", "comment", "includeDeleted"],
    fieldsRu: {
      globalSearch: "Глобальный поиск",
      title: "Наименование",
      comment: "Комментарий",
      includeDeleted: "Включать удаленные",
    },
  },
  "/detectors/download/excel": {
    label: "Извещатели и датчики",
    fields: [
      "globalSearch",
      "title",
      "typeId",
      "typeTitle",
      "minLabor",
      "maxLabor",
      "purpose",
      "comment",
      "includeDeleted",
    ],
    fieldsRu: {
      globalSearch: "Глобальный поиск",
      title: "Наименование датчика",
      typeId: "Тип датчика",
      typeTitle: "Тип датчика",
      minLabor: "Мин. трудоемкость",
      maxLabor: "Макс. трудоемкость",
      purpose: "Назначение",
      comment: "Комментарий",
      includeDeleted: "Включать удаленные",
    },
  },
  "/work_type_codes/download/excel": {
    label: "Коды видов регламентных работ",
    fields: ["globalSearch", "title", "comment", "includeDeleted"],
    fieldsRu: {
      globalSearch: "Глобальный поиск",
      title: "Наименование",
      comment: "Комментарий",
      includeDeleted: "Включать удаленные",
    },
  },
  "/work_types/download/excel": {
    label: "Виды регламентных работ",
    fields: ["globalSearch", "title", "comment", "includeDeleted"],
    fieldsRu: {
      globalSearch: "Глобальный поиск",
      title: "Наименование",
      comment: "Комментарий",
      includeDeleted: "Включать удаленные",
    },
  },
  "/documents/download/excel": {
    label: "Документы",
    fields: [
      "globalSearch",
      "title",
      "comment",
      "documentType",
      "includeDeleted",
    ],
    fieldsRu: {
      globalSearch: "Глобальный поиск",
      title: "Наименование",
      comment: "Комментарий",
      includeDeleted: "Включать удаленные",
      documentType: "Тип документа",
    },
  },
  "/stations/download/excel": {
    label: "Станции",
    fields: [
      "globalSearch",
      "type",
      "stationNumber",
      "inventoryNumber",
      "installationLocation",
      "comment",
      "stationNameId",
      "maintenanceTeamId",
      "orgId",
      "minCapacity",
      "maxCapacity",
      "minNormative",
      "maxNormative",
      "objectsNumberFromMin",
      "objectsNumberToMax",
      "dateEnteredFrom",
      "dateEnteredTo",
      "dateAdjustedFrom",
      "dateAdjustedTo",
      "includeDeleted",
    ],
    fieldsRu: {
      globalSearch: "Глобальный поиск",
      type: "Тип станции",
      stationNumber: "Номер станции",
      inventoryNumber: "Инвентарный номер",
      installationLocation: "Место установки",
      comment: "Комментарий",
      stationNameId: "Наименование станции",
      maintenanceTeamId: "Обслуживающая бригада",
      orgId: "Организация",
      minCapacity: "Мин. емкость",
      maxCapacity: "Макс. емкость",
      minNormative: "Мин. норматив",
      maxNormative: "Макс. норматив",
      objectsNumberFromMin: "Номер объектов 'С'",
      objectsNumberToMax: "Номер объектов 'По'",
      dateEnteredFrom: "Дата ввода 'С'",
      dateEnteredTo: "Дата ввода 'По'",
      dateAdjustedFrom: "Дата корректировки 'С'",
      dateAdjustedTo: "Дата корректировки 'По'",
      includeDeleted: "Включать удаленные",
    },
  },
  "/trains/download/excel": {
    label: "Шлейфы",
    fields: [
      "globalSearch",
      "number",
      "location",
      "coordinates",
      "comment",
      "stationId",
      "maintenanceTeamId",
      "orgId",
      "hidden",
      "sectionNumber",
      "minLabor",
      "maxLabor",
      "dateEnteredFrom",
      "dateEnteredTo",
    ],
    fieldsRu: {
      globalSearch: "Глобальный поиск",
      number: "Номер шлейфа",
      location: "Место установки",
      coordinates: "Координаты установки",
      comment: "Комментарий",
      stationId: "Номер станции",
      maintenanceTeamId: "Обслуживающая бригада",
      orgId: "Организация",
      hidden: "Под потолком",
      sectionNumber: "Номер раздела",
      minLabor: "Мин. трудоемкость",
      maxLabor: "Макс. трудоемкость",
      dateEnteredFrom: "Дата ввода в эксплуатацию 'С'",
      dateEnteredTo: "Дата ввода в эксплуатацию 'По'",
    },
  },
  "/subjects/download/excel": {
    label: "Объекты ОС",
    fields: [
      "globalSearch",
      "number",
      "name",
      "coordinates",
      "phone",
      "comment",
      "stationId",
      "stationNumber",
      "adminStationNumber",
      "orgId",
      "orgShortTitle",
      "maintenanceTeamId",
      "minLabor",
      "maxLabor",
      "dateEnteredFrom",
      "dateEnteredTo",
      "includeDeleted",
    ],
    fieldsRu: {
      globalSearch: "Глобальный поиск",
      number: "Номер объекта",
      name: "Наименование объекта охраны",
      coordinates: "Координаты объекта охраны",
      phone: "Номер телефона",
      comment: "Комментарий",
      stationId: "Номер станции",
      stationNumber: "Номер станции",
      adminStationNumber: "Номер прибора на объекте",
      orgId: "Организация или подразделение",
      orgShortTitle: "Сокращенное наименование организации",
      maintenanceTeamId: "Обслуживающая бригада",
      minLabor: "Минимальная трудоемкость",
      maxLabor: "Максимальная трудоемкость",
      dateEnteredFrom: "Дата ввода в эксплуатацию 'C'",
      dateEnteredTo: "Дата ввода в эксплуатацию 'По'",
      includeDeleted: "Включать удаленные",
    },
  },
};
